### ISSUE TITLE
Documentação não atrai novos adeptos

### ISSUE THREAD

**Issue by leonardovilarinho** [jails-org/Jails#2]
O ideal não era comentar aqui mas não encontrei outro lugar, o framework parece ser muito bom, a ideia é sensacional, mas falta documentação, talvez um ebook dizendo o zero como funciona, como instalar e usar ele, principalmente na segunda versão, que não se encontra quase nada falando. Como sou iniciante no desenvolvimento Front-End com JS fiquei perdido.

**Comment by Javiani** [comment]
@leonardovilarinho acho que pode comentar aqui sim, isso é um issue, e agradeço muito o feedback. É muito importante pra mim críticas construtivas como a sua.
Vou melhorar a documentação, futuramente adicionar alguns vídeos também para ajudar.

Obrigado!

**Comment by leonardovilarinho** [comment]
Obrigado pela atenção, vou dar uma olhada novamente, durante esses dias iniciei no VueJS e deu pra entender muita coisa que ambos tem em comum. Creio que agora dê para iniciar e contribuir com o Jails.

**Comment by Javiani** [comment]
@leonardovilarinho O VueJS é uma excelente opção! Tem ótimos vídeos e a comunidade é bem ativa. Aqui tem uma série de vídeos que eu curti bastante: https://laracasts.com/series/learning-vue-step-by-step/episodes/1

A diferença primordial do `Jails` com relação ao Vue e outras bibliotecas de componentes é que o `Jails` tentará sempre seguir os padrões web, direcionando o desenvolvimento mais próximo possível do que já conhecemos usando o js puro, ou com jquery.

O Vuejs, assim como o Angular 1 possui muitos verbos próprios e muitas interfaces próprias. As diretivas são coisas completamente novas e não tem muito haver com o html que já usamos. Então exige ainda uma curva de aprendizado considerável. Porém é mais potente sem dúvida do que o `Jails`.

O intuito do Jails é simplificar ao máximo, não inserir muitas coisas novas, principalmente para iniciantes e depender sempre dos componentes para evoluir, não sendo necessário muita atualização no seu core.
