### ISSUE TITLE
can't find jai path when 'jai' is aliased on linux

### ISSUE THREAD

**Issue by EriKWDev** [jails-org/Jails#8]
I am on linux and have an alias 'jai' for 'jai-linux'. This seems to confuse the `find_jai_path` since `whereis` still returns something

```console
> whereis jai
jai:
```

but `whereis jai-linux` still works.

I see there is a fallback in the function to instead look for `jai-linux` or `jai-macos` depending on os, but seems for me that the function only works if the correct name is supplied from the start.

I did the following as a default instead of the current main

```go
// in main
    if server.args.jai_path.count == 0 {
        server.args.jai_path = find_jai_path_depending_on_os();
        log("Jai path: %", server.args.jai_path);
    }

// and then
find_jai_path_depending_on_os :: () -> string {
    #if OS == .MACOS {
        return find_jai_path("jai-macos");
    } else #if OS == .LINUX {
        return find_jai_path("jai-linux");
    } else {
        return find_jai_path("jai");
    }
}
```

**Comment by Javiani** [comment]
Hey @EriKWDev, 
I think you're in the wrong repo... This one is related to a Javascript Browser library.

**Comment by EriKWDev** [comment]
lol yup
